### ISSUE TITLE
Kext won't load macOS 10.15.4 (19E287)

### ISSUE THREAD

**Issue by HiImWeird** [AppleIntelWifi/adapter#49]
Tried using the scripts in the folder to load the kext and have tried using kextload but get "failed to load - (libkern/kext) not found.
AC 3160, macOS 10.15.4 (19E287)
Not sure if this is the right place for this issue will remove if needed.
[log.txt](https://github.com/AppleIntelWifi/adapter/files/4458638/log.txt)

**Comment by rv32ima** [comment]
This is related to the massive overhaul I have to do...

**Comment by HiImWeird** [comment]
ah, I see.
Thanks for all your hard work.

**Comment by bin** [comment]
@hatf0 Might you be able to provide additional detail on what is causing this?  

Thank you for your work on this.

**Comment by rv32ima** [comment]
@bin `kxld` (or, the kernel linker) requires that all symbols defined in header files have a counterpart within source files, including functions. With that 802.11 commit, I pulled in a bunch of new source for the 802.11 stack (as zxy and I are working together on making a Better :TM: 802.11 stack) but which left several symbols undefined. To put it simply, kxld doesn't like that. This should be fixed by the fact that I just reverted that commit. I did not like the amount of code bloat it added, and I think we can do without it.

**Comment by mrusso99** [comment]
> @bin `kxld` (or, the kernel linker) requires that all symbols defined in header files have a counterpart within source files, including functions. With that 802.11 commit, I pulled in a bunch of new source for the 802.11 stack (as zxy and I are working together on making a Better :TM: 802.11 stack) but which left several symbols undefined. To put it simply, kxld doesn't like that. This should be fixed by the fact that I just reverted that commit. I did not like the amount of code bloat it added, and I think we can do without it.

Well unfortunetely it seems not, i have still the same issue (i have a 9260 AC)

**Comment by rv32ima** [comment]
@hmuny99 I... just published a kext to fix that? Please download the latest kext and double check.

**Comment by bin** [comment]
@hatf0 Thanks for the info and the fix.  The kext loads fine now.

**Comment by rv32ima** [comment]
I believe this is fixed?
